# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$env_var $all"""

[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

[python]
symbol = "🐍 "
python_binary = "python3"
disabled = false

[git_branch]
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style) "
disabled = false

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
disabled = false

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "
disabled = false

